<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\WorkFlowHub.Domain\WorkFlowHub.Domain.csproj" />
    <ProjectReference Include="..\WorkFlowHub.Application\WorkFlowHub.Application.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Data\" />
    <Folder Include="Identity\" />
    <Folder Include="Configurations\" />
    <Folder Include="Services\" />
    <Folder Include="Repositories\" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

</Project>
